language: objective-c

osx_image: xcode9.1

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.coursier
  - $HOME/.sbt
  - platform
  - apps

install:
  - bin/prelude.sh

script:
  - bin/sbt-launch.sh clean test:compile test:fastOptJS
  - travis_wait 60 bin/sbt-launch.sh --error test
