version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true

clone_folder: c:\sireum-v3

before_build:
  - cmd: git config core.symlinks true
  - cmd: git reset --hard
  - cmd: git submodule update -q --init --recursive

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
  PATH: 'C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%'

cache:
  - '%USERPROFILE%\.sbt' -> project/build.properties
  - '%USERPROFILE%\.coursier' -> versions.properties
  - '%LOCALAPPDATA%\Coursier\cache' -> versions.properties
  - platform -> bin\prelude.sh
  - apps -> bin\prelude.sh

install:
  - bash -lc "pacman --noconfirm -S unzip bc"
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/prelude.sh"

build_script:
  - bash -lc "$APPVEYOR_BUILD_FOLDER/bin/sbt-launch.sh clean test:compile test:fastOptJS"

test_script:
  - bash -lc "SIREUM_PARALLEL_BUILD=false $APPVEYOR_BUILD_FOLDER/bin/sbt-launch.sh 'project sireum-jvm' test"
